org.gradle.jvmargs=-Xmx4096M
#org.gradle.jvmargs=-Xmx2048M

# Project Details
p_name = Beryllium
p_id = beryllium
p_group = me.zombii.beryllium
p_desc = This is the example mod\
  for Cosmic\
  Reach
p_author = YOU!
p_version = 1.0.0-alpha

# Cosmic Reach
cosmic_reach_version = 0.5.25-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.2-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

fastutil_version = 8.5.18
